name: Moodle Plugin CI

on: [push, pull_request, workflow_dispatch]

jobs:
  citest:
    name: CI test
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
            database: 'pgsql'
            moodle-branch: 'master'
            node-version: '14.15.0'
          - php: '7.3'
            database: 'mariadb'
            moodle-branch: 'MOODLE_310_STABLE'
            node-version: '14.15.0'
          - php: '7.0'
            database: 'pgsql'
            moodle-branch: 'MOODLE_35_STABLE'
            node-version: '14.15.0'

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: plugin

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pgsql, zip, gd
        coverage: none
        
    - name: Initialise moodle-plugin-ci
      run: |
        make init
        cp -R tests/Fixture/moodle-local_ci ../moodle-local_ci
        echo $(cd bin; pwd) >> $GITHUB_PATH
        echo $(cd vendor/bin; pwd) >> $GITHUB_PATH
        echo "TRAVIS_BUILD_DIR="$(cd ../moodle-local_ci; pwd) >> $GITHUB_ENV
        # PHPUnit depends on en_AU.UTF-8 locale
        sudo locale-gen en_AU.UTF-8
        # Define NVM_DIR pointing to nvm installation.
        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
    - name: Install moodle-plugin-ci
      run: moodle-plugin-ci install -vvv
      env:
        DB: 'pgsql'
        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
        IGNORE_PATHS: 'ignore'
        IGNORE_NAMES: 'ignore_name.php'
        MUSTACHE_IGNORE_NAMES: 'broken.mustache'

    - name: Run Integration tests
      env:
        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
      run: |
        moodle-plugin-ci phplint
        moodle-plugin-ci phpmd
        moodle-plugin-ci codechecker
        moodle-plugin-ci validate
        moodle-plugin-ci savepoints
        moodle-plugin-ci mustache
        moodle-plugin-ci grunt ||  [ \
            "$MOODLE_BRANCH" != 'master' -a  ]
        moodle-plugin-ci phpunit --verbose --coverage-text
        moodle-plugin-ci behat --profile default
        moodle-plugin-ci behat --profile chrome
